-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "end_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "start_date_toRegister" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "end_date_toRegister" SET DATA TYPE TIMESTAMPTZ(3);
